### ISSUE TITLE
Specification documentation update topics

### ISSUE THREAD

**Issue by RieksJ** [tno-terminology-design/tev2-specifications#22]
Here's a list of topics that need to be updated in the specifications documentation:

- [ ] We need 'guides' that help users for particular purposes, such as getting started, how to do termrefs, how to create HRGs, and so on. Guides are about how to use tools and other technical stuff. They are not about methods/processes/procedures for devising terminologies.
- [x] Rewrite documentation regarding the text conversion process as used in various tools. Properly specify converters, moustache profiles, and the like.
- [ ] Ensure the documentation covers issue https://github.com/tno-terminology-design/tev2-tools/issues/7.
- [ ] Ensure the documentation has explainations to prevent reraising issue https://github.com/tno-terminology-design/tev2-tools/issues/11.
- [x] Ensure the documentation covers issue https://github.com/tno-terminology-design/tev2-tools/issues/19.
